### ISSUE TITLE
Updating the readme

### ISSUE THREAD

**Issue by merlin-ke** [nccgroup/thetick#1]
Great tool you have. Still finding my way round it.
A few issues i think can improve user experience.I found the Readme to be a bit high level especially for guys not very familiar with compiling files. 
This are some of my suggestions.
For **make clean** && **make** to work, users must be in the **src** folder. Once the command has run to completion,  a new folder bin will be created. This folder contains the backdoor that you will put on the target system.
After running the **./ticksvc ip.here porthere**.  On the control machine,  type **bots**. This will show a listing of all bots. To connect to a bot, type **use 0** where 0 is the boot number.

**Comment by MarioVilas** [comment]
Thanks for your kind words and suggestion! I've expanded the README a bit more so it should hopefully be clearer now :)
