### ISSUE TITLE
pull function is abnormal！！！

### ISSUE THREAD

**Issue by boomshy** [nccgroup/thetick#6]
the func in parser.h is void parser_begin_response(Parser *parser, uint8_t status, uint16_t length);
but used as parser_begin_response(Parser *parser, uint8_t status, uint32_t length); in file.c
When the file is too large, it will cause integer overflow, resulting in abnormal pull function

**Comment by MarioVilas** [comment]
I'm sorry, but I see the same definition in both .h and .c and it's uint16_t. (Also, it would not compile if the definition was wrong).

parser.h:
https://github.com/nccgroup/thetick/blob/db47ab07367390d7f75cc2199d1a0ebb8cf1dee7/src/parser.h#L127

parser.c:
https://github.com/nccgroup/thetick/blob/db47ab07367390d7f75cc2199d1a0ebb8cf1dee7/src/parser.c#L89

Do you have a way to reproduce the bug? If you're experiencing a crash it could be somewhere else. Closing the ticket for now.
